import SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_goal_check

open SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_goal.VC_Correct where
  proof_of_optimized_selection_sort_safety_wit_1 := proof_of_optimized_selection_sort_safety_wit_1
  proof_of_optimized_selection_sort_safety_wit_2 := proof_of_optimized_selection_sort_safety_wit_2
  proof_of_optimized_selection_sort_safety_wit_3 := proof_of_optimized_selection_sort_safety_wit_3
  proof_of_optimized_selection_sort_safety_wit_4 := proof_of_optimized_selection_sort_safety_wit_4
  proof_of_optimized_selection_sort_safety_wit_5 := proof_of_optimized_selection_sort_safety_wit_5
  proof_of_optimized_selection_sort_safety_wit_6 := proof_of_optimized_selection_sort_safety_wit_6
  proof_of_optimized_selection_sort_safety_wit_7 := proof_of_optimized_selection_sort_safety_wit_7
  proof_of_optimized_selection_sort_safety_wit_8 := proof_of_optimized_selection_sort_safety_wit_8
  proof_of_optimized_selection_sort_safety_wit_9 := proof_of_optimized_selection_sort_safety_wit_9
  proof_of_optimized_selection_sort_entail_wit_3_1 := proof_of_optimized_selection_sort_entail_wit_3_1
  proof_of_optimized_selection_sort_entail_wit_3_2 := proof_of_optimized_selection_sort_entail_wit_3_2
  proof_of_optimized_selection_sort_partial_solve_wit_1 := proof_of_optimized_selection_sort_partial_solve_wit_1
  proof_of_optimized_selection_sort_partial_solve_wit_2 := proof_of_optimized_selection_sort_partial_solve_wit_2
  proof_of_optimized_selection_sort_partial_solve_wit_3 := proof_of_optimized_selection_sort_partial_solve_wit_3
  proof_of_optimized_selection_sort_partial_solve_wit_4 := proof_of_optimized_selection_sort_partial_solve_wit_4
  proof_of_optimized_selection_sort_partial_solve_wit_5 := proof_of_optimized_selection_sort_partial_solve_wit_5
  proof_of_optimized_selection_sort_partial_solve_wit_6 := proof_of_optimized_selection_sort_partial_solve_wit_6
  proof_of_optimized_selection_sort_entail_wit_1 := proof_of_optimized_selection_sort_entail_wit_1
  proof_of_optimized_selection_sort_entail_wit_2 := proof_of_optimized_selection_sort_entail_wit_2
  proof_of_optimized_selection_sort_entail_wit_4_1 := proof_of_optimized_selection_sort_entail_wit_4_1
  proof_of_optimized_selection_sort_entail_wit_4_2 := proof_of_optimized_selection_sort_entail_wit_4_2
  proof_of_optimized_selection_sort_return_wit_1 := proof_of_optimized_selection_sort_return_wit_1

end SimpleC.EE.LLM_bench.Algorithms.optimized_selection_sort.optimized_selection_sort_goal_check
