import SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_goal_check

open SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_goal.VC_Correct where
  proof_of_modular_inverse_safety_wit_1 := proof_of_modular_inverse_safety_wit_1
  proof_of_modular_inverse_safety_wit_2 := proof_of_modular_inverse_safety_wit_2
  proof_of_modular_inverse_safety_wit_3 := proof_of_modular_inverse_safety_wit_3
  proof_of_modular_inverse_partial_solve_wit_1_pure := proof_of_modular_inverse_partial_solve_wit_1_pure
  proof_of_modular_inverse_partial_solve_wit_1 := proof_of_modular_inverse_partial_solve_wit_1
  proof_of_modular_inverse_return_wit_1 := proof_of_modular_inverse_return_wit_1
  proof_of_modular_inverse_return_wit_2 := proof_of_modular_inverse_return_wit_2

end SimpleC.EE.LLM_bench.Algorithms.modular_inverse.modular_inverse_goal_check
