import SimpleC.EE.LLM_bench.Algorithms.merging_stones.merging_stones_goal_check

open SimpleC.EE.LLM_bench.Algorithms.merging_stones.merging_stones_lib
open SimpleC.EE.LLM_bench.Algorithms.merging_stones.merging_stones_proof_manual

-- All 29 library Qed and 73 manual Qed retain their Coq public names.
-- The 49 source auto Admitted remain separate and may not enter these completed proofs.
run_cmd do
  let proved := #[
    ``list_sum_bounds__arithmetic_safety,
    ``stone_interval_sum_bounds__arithmetic_safety,
    ``sum_lower_bound__prefix_math,
    ``StoneMassesBounded_Znth__prefix_math,
    ``StoneMassesBounded_sublist_sum_bounds__prefix_math,
    ``StonePrefixProgress_value_bounds__prefix_math,
    ``StonePrefixProgress_extend__prefix_math,
    ``StonePrefixDone_interval_sum__prefix_math,
    ``StonePrefixDone_interval_bounds__prefix_math,
    ``StoneSplitProgress_initial__prefix_math,
    ``StoneZeroProgress_store__zero_table,
    ``StoneIntervalMin_singleton__zero_table,
    ``StoneLenDone_two_of_zero__zero_table,
    ``StoneIntervalSum_bounds__interval_min_core,
    ``StoneMergePlan_bounds__interval_min_core,
    ``StoneIntervalMin_precise_bounds__interval_min_core,
    ``StoneIntervalMin_bounds__interval_min_core,
    ``StoneLenDone_entry_bounds__interval_min_core,
    ``StoneLenDone_entry_precise_bounds__interval_min_core,
    ``StoneSplitProgress_child_bounds__interval_min_core,
    ``StoneSplitProgress_candidate_facts__interval_min_core,
    ``StoneSplitProgress_table_shape__interval_min_core,
    ``StoneSplitProgress_complete__interval_min_core,
    ``StoneLenDone_final_facts__interval_min_core,
    ``StoneSplitProgress_keep_best__split_loop_step,
    ``StoneSplitProgress_replace_best__split_loop_step,
    ``StoneLenDone_to_initial_left_progress__table_progress,
    ``StoneUpdatedCell_to_next_left_progress__table_progress,
    ``StoneLeftProgress_to_next_len_done__table_progress,
    ``proof_of_mergingStones_safety_wit_6_split_goal_1,
    ``proof_of_mergingStones_safety_wit_6_split_goal_2,
    ``proof_of_mergingStones_safety_wit_6,
    ``proof_of_mergingStones_safety_wit_20_split_goal_1,
    ``proof_of_mergingStones_safety_wit_20_split_goal_2,
    ``proof_of_mergingStones_safety_wit_20,
    ``proof_of_mergingStones_entail_wit_1_split_goal_1,
    ``proof_of_mergingStones_entail_wit_1_split_goal_spatial,
    ``proof_of_mergingStones_entail_wit_1,
    ``proof_of_mergingStones_entail_wit_2,
    ``proof_of_mergingStones_entail_wit_3_split_goal_1,
    ``proof_of_mergingStones_entail_wit_3_split_goal_2,
    ``proof_of_mergingStones_entail_wit_3_split_goal_3,
    ``proof_of_mergingStones_entail_wit_3_split_goal_4,
    ``proof_of_mergingStones_entail_wit_3,
    ``proof_of_mergingStones_entail_wit_4_split_goal_1,
    ``proof_of_mergingStones_entail_wit_4,
    ``proof_of_mergingStones_entail_wit_5_split_goal_1,
    ``proof_of_mergingStones_entail_wit_5_split_goal_2,
    ``proof_of_mergingStones_entail_wit_5,
    ``proof_of_mergingStones_entail_wit_6_split_goal_1,
    ``proof_of_mergingStones_entail_wit_6,
    ``proof_of_mergingStones_entail_wit_7_split_goal_1,
    ``proof_of_mergingStones_entail_wit_7,
    ``proof_of_mergingStones_entail_wit_8,
    ``proof_of_mergingStones_entail_wit_9_split_goal_1,
    ``proof_of_mergingStones_entail_wit_9,
    ``proof_of_mergingStones_entail_wit_11_split_goal_1,
    ``proof_of_mergingStones_entail_wit_11_split_goal_2,
    ``proof_of_mergingStones_entail_wit_11,
    ``proof_of_mergingStones_entail_wit_13_split_goal_1,
    ``proof_of_mergingStones_entail_wit_13,
    ``proof_of_mergingStones_entail_wit_14_split_goal_1,
    ``proof_of_mergingStones_entail_wit_14_split_goal_2,
    ``proof_of_mergingStones_entail_wit_14_split_goal_3,
    ``proof_of_mergingStones_entail_wit_14_split_goal_4,
    ``proof_of_mergingStones_entail_wit_14,
    ``proof_of_mergingStones_entail_wit_16_split_goal_1,
    ``proof_of_mergingStones_entail_wit_16_split_goal_2,
    ``proof_of_mergingStones_entail_wit_16_split_goal_3,
    ``proof_of_mergingStones_entail_wit_16_split_goal_4,
    ``proof_of_mergingStones_entail_wit_16,
    ``proof_of_mergingStones_entail_wit_17,
    ``proof_of_mergingStones_entail_wit_18,
    ``proof_of_mergingStones_entail_wit_19_1_split_goal_1,
    ``proof_of_mergingStones_entail_wit_19_1,
    ``proof_of_mergingStones_entail_wit_19_2_split_goal_1,
    ``proof_of_mergingStones_entail_wit_19_2_split_goal_2,
    ``proof_of_mergingStones_entail_wit_19_2,
    ``proof_of_mergingStones_entail_wit_20_split_goal_1,
    ``proof_of_mergingStones_entail_wit_20_split_goal_2,
    ``proof_of_mergingStones_entail_wit_20_split_goal_3,
    ``proof_of_mergingStones_entail_wit_20_split_goal_4,
    ``proof_of_mergingStones_entail_wit_20,
    ``proof_of_mergingStones_entail_wit_21_split_goal_1,
    ``proof_of_mergingStones_entail_wit_21_split_goal_2,
    ``proof_of_mergingStones_entail_wit_21_split_goal_3,
    ``proof_of_mergingStones_entail_wit_21,
    ``proof_of_mergingStones_entail_wit_22,
    ``proof_of_mergingStones_entail_wit_23_split_goal_1,
    ``proof_of_mergingStones_entail_wit_23_split_goal_2,
    ``proof_of_mergingStones_entail_wit_23,
    ``proof_of_mergingStones_entail_wit_24_split_goal_1,
    ``proof_of_mergingStones_entail_wit_24,
    ``proof_of_mergingStones_entail_wit_25_split_goal_1,
    ``proof_of_mergingStones_entail_wit_25_split_goal_2,
    ``proof_of_mergingStones_entail_wit_25,
    ``proof_of_mergingStones_entail_wit_26_split_goal_1,
    ``proof_of_mergingStones_entail_wit_26_split_goal_2,
    ``proof_of_mergingStones_entail_wit_26_split_goal_3,
    ``proof_of_mergingStones_entail_wit_26_split_goal_4,
    ``proof_of_mergingStones_entail_wit_26,
    ``proof_of_mergingStones_return_wit_1]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Completed merging_stones proof {decl} depends on sorryAx"
