import SimpleC.EE.LLM_bench.Algorithms.matrix_chain_multiplication.matrix_chain_multiplication_goal_check

open SimpleC.EE.LLM_bench.Algorithms.matrix_chain_multiplication.matrix_chain_multiplication_lib
open SimpleC.EE.LLM_bench.Algorithms.matrix_chain_multiplication.matrix_chain_multiplication_proof_manual

-- All 7 library Qed and 59 manual Qed retain their Coq public names.
-- The 63 source auto Admitted are inherited separately and cannot enter these proofs.
run_cmd do
  let proved := #[
    ``matrix_chain_zero_table_lengths_done__initialization,
    ``matrix_chain_plan_linear_upper_bound__candidate_progress,
    ``matrix_chain_interval_minimum_upper_bound__candidate_progress,
    ``matrix_chain_split_progress_initial__candidate_progress,
    ``matrix_chain_split_progress_better__min_update,
    ``matrix_chain_split_progress_not_better__min_update,
    ``matrix_chain_split_progress_complete__min_update,
    ``proof_of_matrixChainMinCost_entail_wit_1_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_1,
    ``proof_of_matrixChainMinCost_entail_wit_2_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_2,
    ``proof_of_matrixChainMinCost_entail_wit_3,
    ``proof_of_matrixChainMinCost_entail_wit_5_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_5,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_3,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_4,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_5,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_6,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_7,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_8,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_9,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_10,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_11,
    ``proof_of_matrixChainMinCost_entail_wit_6_split_goal_12,
    ``proof_of_matrixChainMinCost_entail_wit_6,
    ``proof_of_matrixChainMinCost_entail_wit_7_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_7_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_7,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_3,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_4,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_5,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_6,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_7,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_8,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_9,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_10,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_11,
    ``proof_of_matrixChainMinCost_entail_wit_8_split_goal_12,
    ``proof_of_matrixChainMinCost_entail_wit_8,
    ``proof_of_matrixChainMinCost_entail_wit_9_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_9_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_9,
    ``proof_of_matrixChainMinCost_entail_wit_10_1_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_10_1,
    ``proof_of_matrixChainMinCost_entail_wit_10_2_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_10_2,
    ``proof_of_matrixChainMinCost_entail_wit_11_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_11_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_11_split_goal_3,
    ``proof_of_matrixChainMinCost_entail_wit_11,
    ``proof_of_matrixChainMinCost_entail_wit_12_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_12_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_12_split_goal_3,
    ``proof_of_matrixChainMinCost_entail_wit_12,
    ``proof_of_matrixChainMinCost_entail_wit_13_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_13,
    ``proof_of_matrixChainMinCost_entail_wit_14_split_goal_1,
    ``proof_of_matrixChainMinCost_entail_wit_14_split_goal_2,
    ``proof_of_matrixChainMinCost_entail_wit_14_split_goal_3,
    ``proof_of_matrixChainMinCost_entail_wit_14_split_goal_4,
    ``proof_of_matrixChainMinCost_entail_wit_14_split_goal_5,
    ``proof_of_matrixChainMinCost_entail_wit_14]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Completed matrix_chain_multiplication proof {decl} depends on sorryAx"
