import SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_goal_check

open SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_goal.VC_Correct where
  proof_of_initCounts_safety_wit_1 := proof_of_initCounts_safety_wit_1
  proof_of_initCounts_safety_wit_2 := proof_of_initCounts_safety_wit_2
  proof_of_initCounts_safety_wit_3 := proof_of_initCounts_safety_wit_3
  proof_of_initCounts_safety_wit_4 := proof_of_initCounts_safety_wit_4
  proof_of_initCounts_entail_wit_3 := proof_of_initCounts_entail_wit_3
  proof_of_initCounts_partial_solve_wit_1 := proof_of_initCounts_partial_solve_wit_1
  proof_of_initCounts_partial_solve_wit_2 := proof_of_initCounts_partial_solve_wit_2
  proof_of_copyCounts_safety_wit_1 := proof_of_copyCounts_safety_wit_1
  proof_of_copyCounts_safety_wit_2 := proof_of_copyCounts_safety_wit_2
  proof_of_copyCounts_entail_wit_3 := proof_of_copyCounts_entail_wit_3
  proof_of_copyCounts_partial_solve_wit_1 := proof_of_copyCounts_partial_solve_wit_1
  proof_of_copyCounts_partial_solve_wit_2 := proof_of_copyCounts_partial_solve_wit_2
  proof_of_countChoosingInns_safety_wit_1 := proof_of_countChoosingInns_safety_wit_1
  proof_of_countChoosingInns_safety_wit_2 := proof_of_countChoosingInns_safety_wit_2
  proof_of_countChoosingInns_safety_wit_3 := proof_of_countChoosingInns_safety_wit_3
  proof_of_countChoosingInns_safety_wit_4 := proof_of_countChoosingInns_safety_wit_4
  proof_of_countChoosingInns_safety_wit_5 := proof_of_countChoosingInns_safety_wit_5
  proof_of_countChoosingInns_safety_wit_6 := proof_of_countChoosingInns_safety_wit_6
  proof_of_countChoosingInns_safety_wit_7 := proof_of_countChoosingInns_safety_wit_7
  proof_of_countChoosingInns_safety_wit_8 := proof_of_countChoosingInns_safety_wit_8
  proof_of_countChoosingInns_safety_wit_9 := proof_of_countChoosingInns_safety_wit_9
  proof_of_countChoosingInns_safety_wit_10 := proof_of_countChoosingInns_safety_wit_10
  proof_of_countChoosingInns_entail_wit_7_1 := proof_of_countChoosingInns_entail_wit_7_1
  proof_of_countChoosingInns_entail_wit_7_2 := proof_of_countChoosingInns_entail_wit_7_2
  proof_of_countChoosingInns_return_wit_1 := proof_of_countChoosingInns_return_wit_1
  proof_of_countChoosingInns_partial_solve_wit_1 := proof_of_countChoosingInns_partial_solve_wit_1
  proof_of_countChoosingInns_partial_solve_wit_2 := proof_of_countChoosingInns_partial_solve_wit_2
  proof_of_countChoosingInns_partial_solve_wit_3 := proof_of_countChoosingInns_partial_solve_wit_3
  proof_of_countChoosingInns_partial_solve_wit_4 := proof_of_countChoosingInns_partial_solve_wit_4
  proof_of_countChoosingInns_partial_solve_wit_5 := proof_of_countChoosingInns_partial_solve_wit_5
  proof_of_countChoosingInns_partial_solve_wit_6 := proof_of_countChoosingInns_partial_solve_wit_6
  proof_of_countChoosingInns_partial_solve_wit_7 := proof_of_countChoosingInns_partial_solve_wit_7
  proof_of_countChoosingInns_partial_solve_wit_8 := proof_of_countChoosingInns_partial_solve_wit_8
  proof_of_countChoosingInns_partial_solve_wit_9 := proof_of_countChoosingInns_partial_solve_wit_9
  proof_of_countChoosingInns_partial_solve_wit_10 := proof_of_countChoosingInns_partial_solve_wit_10
  proof_of_initCounts_entail_wit_1 := proof_of_initCounts_entail_wit_1
  proof_of_initCounts_entail_wit_2 := proof_of_initCounts_entail_wit_2
  proof_of_initCounts_return_wit_1 := proof_of_initCounts_return_wit_1
  proof_of_copyCounts_entail_wit_1 := proof_of_copyCounts_entail_wit_1
  proof_of_copyCounts_entail_wit_2 := proof_of_copyCounts_entail_wit_2
  proof_of_copyCounts_return_wit_1 := proof_of_copyCounts_return_wit_1
  proof_of_countChoosingInns_entail_wit_1 := proof_of_countChoosingInns_entail_wit_1
  proof_of_countChoosingInns_entail_wit_2 := proof_of_countChoosingInns_entail_wit_2
  proof_of_countChoosingInns_entail_wit_3 := proof_of_countChoosingInns_entail_wit_3
  proof_of_countChoosingInns_entail_wit_4 := proof_of_countChoosingInns_entail_wit_4
  proof_of_countChoosingInns_entail_wit_5 := proof_of_countChoosingInns_entail_wit_5
  proof_of_countChoosingInns_entail_wit_6 := proof_of_countChoosingInns_entail_wit_6
  proof_of_countChoosingInns_entail_wit_8 := proof_of_countChoosingInns_entail_wit_8
  proof_of_countChoosingInns_partial_solve_wit_1_pure := proof_of_countChoosingInns_partial_solve_wit_1_pure
  proof_of_countChoosingInns_partial_solve_wit_7_pure := proof_of_countChoosingInns_partial_solve_wit_7_pure

end SimpleC.EE.LLM_bench.Algorithms.choosing_inns.choosing_inns_goal_check
