import SimpleC.EE.LLM_bench.Algorithms.non_overlapping_intervals.non_overlapping_intervals_goal_check
open SimpleC.EE.LLM_bench.Algorithms.non_overlapping_intervals.non_overlapping_intervals_lib
open SimpleC.EE.LLM_bench.Algorithms.non_overlapping_intervals.non_overlapping_intervals_proof_manual

run_cmd do
  let proved := #[
    ``replace_Znth_swap_form__swap_records,
    ``permutation_swap_Znth_lt__swap_records,
    ``replace_nth_comm_Z__swap_records,
    ``replace_Znth_comm__swap_records,
    ``interval_swap_permutation__swap_records,
    ``interval_swap_bounds__swap_records,
    ``pair_intervals_swap__swap_records,
    ``pair_intervals_lengths_and_fields__partition_lomuto,
    ``interval_same_outside_range_refl__partition_lomuto,
    ``interval_swap_length__partition_lomuto,
    ``interval_swap_Znth_left__partition_lomuto,
    ``interval_swap_Znth_right__partition_lomuto,
    ``interval_swap_Znth_other__partition_lomuto,
    ``interval_same_outside_range_swap_inside__partition_lomuto,
    ``lomuto_scan_init__partition_lomuto,
    ``lomuto_scan_accept__partition_lomuto,
    ``lomuto_scan_skip__partition_lomuto,
    ``lomuto_scan_finish__partition_lomuto,
    ``Forall_Znth_interval__quicksort_left,
    ``Forall_sublist_interval__quicksort_left,
    ``sublist_interval_eq_from_Znth__quicksort_left,
    ``list_interval_decompose_sublist__quicksort_left,
    ``interval_same_outside_prefix__quicksort_left,
    ``interval_same_outside_suffix__quicksort_left,
    ``interval_middle_permutation__quicksort_left,
    ``partition_preserved_by_left_sort__quicksort_left,
    ``outside_range_compose_nested__quicksort_left,
    ``sorted_range_empty__quicksort_left,
    ``outside_range_compose_nested__quicksort_finish,
    ``Forall_interval_permutation__quicksort_finish,
    ``Forall_Znth_interval__quicksort_finish,
    ``Forall_sublist_interval_by_Znth__quicksort_finish,
    ``sublist_eq_from_Znth_interval__quicksort_finish,
    ``list_decompose_sublist_interval__quicksort_finish,
    ``same_outside_prefix_interval__quicksort_finish,
    ``same_outside_suffix_interval__quicksort_finish,
    ``middle_permutation_interval__quicksort_finish,
    ``right_sort_preserves_left_partition__quicksort_finish,
    ``sorted_range_preserved_on_left__quicksort_finish,
    ``partition_merge_sorted_ranges__quicksort_finish,
    ``sorted_range_trivial__quicksort_finish,
    ``same_outside_refl__quicksort_finish,
    ``sorted_full_range__quicksort_finish,
    ``forall_znth__greedy_prefix,
    ``nonoverlap_strongly_sorted__greedy_prefix,
    ``nonoverlap_remove_middle__greedy_prefix,
    ``interval_selection_extend_cases__greedy_prefix,
    ``interval_selection_extend_schedule_cases__greedy_prefix,
    ``prefix_snoc__greedy_prefix,
    ``interval_bounds_prefix__greedy_prefix,
    ``interval_bounds_selected__greedy_prefix,
    ``selected_member_end_le_current__greedy_prefix,
    ``nonoverlap_member_end_le_finish__greedy_prefix,
    ``interval_selection_append__greedy_prefix,
    ``nonoverlap_append__greedy_prefix,
    ``schedule_finish_snoc__greedy_prefix,
    ``nonoverlap_snoc_previous_finish__greedy_prefix,
    ``latest_interval_right_nil__greedy_prefix,
    ``greedy_prefix_accept__greedy_prefix,
    ``interval_selection_retain__greedy_prefix,
    ``selected_finish_end_le_current__greedy_prefix,
    ``greedy_prefix_skip__greedy_prefix,
    ``pair_intervals_fields_at__greedy_prefix,
    ``greedy_prefix_singleton__greedy_prefix,
    ``greedy_prefix_yields_minimum_removals__optimum_returns,
    ``minimum_removals_empty__optimum_returns,
    ``proof_of_swap_intervals_return_wit_1,
    ``proof_of_partition_intervals_entail_wit_1,
    ``proof_of_partition_intervals_entail_wit_2_1,
    ``proof_of_partition_intervals_entail_wit_2_2,
    ``proof_of_partition_intervals_return_wit_1,
    ``proof_of_quicksort_intervals_range_entail_wit_1_1,
    ``proof_of_quicksort_intervals_range_entail_wit_1_2,
    ``proof_of_quicksort_intervals_range_return_wit_1,
    ``proof_of_quicksort_intervals_range_return_wit_2,
    ``proof_of_quicksort_intervals_range_return_wit_3,
    ``proof_of_quicksort_intervals_return_wit_1,
    ``proof_of_eraseOverlapIntervals_entail_wit_1,
    ``proof_of_eraseOverlapIntervals_entail_wit_2_1,
    ``proof_of_eraseOverlapIntervals_entail_wit_2_2,
    ``proof_of_eraseOverlapIntervals_entail_wit_3,
    ``proof_of_eraseOverlapIntervals_return_wit_1,
    ``proof_of_eraseOverlapIntervals_return_wit_2]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Completed interval proof {decl} depends on sorryAx"
