import SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_goal_check

open SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_goal.VC_Correct where
  proof_of_linear_modular_inverse_safety_wit_1 := proof_of_linear_modular_inverse_safety_wit_1
  proof_of_linear_modular_inverse_safety_wit_2 := proof_of_linear_modular_inverse_safety_wit_2
  proof_of_linear_modular_inverse_safety_wit_3 := proof_of_linear_modular_inverse_safety_wit_3
  proof_of_linear_modular_inverse_safety_wit_4 := proof_of_linear_modular_inverse_safety_wit_4
  proof_of_linear_modular_inverse_safety_wit_5 := proof_of_linear_modular_inverse_safety_wit_5
  proof_of_linear_modular_inverse_safety_wit_6 := proof_of_linear_modular_inverse_safety_wit_6
  proof_of_linear_modular_inverse_safety_wit_7 := proof_of_linear_modular_inverse_safety_wit_7
  proof_of_linear_modular_inverse_safety_wit_8 := proof_of_linear_modular_inverse_safety_wit_8
  proof_of_linear_modular_inverse_safety_wit_9 := proof_of_linear_modular_inverse_safety_wit_9
  proof_of_linear_modular_inverse_partial_solve_wit_1 := proof_of_linear_modular_inverse_partial_solve_wit_1
  proof_of_linear_modular_inverse_partial_solve_wit_2 := proof_of_linear_modular_inverse_partial_solve_wit_2
  proof_of_linear_modular_inverse_partial_solve_wit_3 := proof_of_linear_modular_inverse_partial_solve_wit_3
  proof_of_linear_modular_inverse_entail_wit_1 := proof_of_linear_modular_inverse_entail_wit_1
  proof_of_linear_modular_inverse_entail_wit_2 := proof_of_linear_modular_inverse_entail_wit_2
  proof_of_linear_modular_inverse_entail_wit_3 := proof_of_linear_modular_inverse_entail_wit_3
  proof_of_linear_modular_inverse_return_wit_1 := proof_of_linear_modular_inverse_return_wit_1

end SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse.linear_modular_inverse_goal_check
