import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_goal_check

run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.sublist_snoc_at_index__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.occurrences_sublist_snoc_eq__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.occurrences_sublist_snoc_neq__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.sublist0_In_Znth_exists__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.paint_scan_state_init__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.paint_scan_state_step_x__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.paint_scan_state_step_first_y__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.paint_scan_state_step_y__scan_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.good_adjacent_sums_uniform__accepted_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.balanced_two_value_permutation__accepted_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.good_adjacent_sums_period_two__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.Znth_drop_two__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.adjacent_sums_tail_values__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.good_adjacent_sums_at_most_two_values__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.occurrences_cons_distinct_pair__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.adjacent_sums_count_balance_core__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.good_adjacent_sums_count_balance__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.Znth_in_range__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.In_sublist_from_zero__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.good_adjacent_sums_no_three_distinct__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_lib.paint_scan_state_full_count_balance__rejected_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_7_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_7_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_7,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_10_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_10_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_10,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_11_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_11_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_11,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_17_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_17_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_17,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_19_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_19_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_safety_wit_19,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_entail_wit_2_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_5_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P004_1890A_doremys_paint_3_proof_manual.proof_of_solver_return_wit_5
  ]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Source Qed {decl} depends on sorryAx"
  Lean.logInfo "CF00 P004: all 55 source Qed recursively audited without sorryAx"
