import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_goal_check

run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_state_initial__initialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_current_raise__current_max_update,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_green_noncurrent__green_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_green_outside_original__green_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.first_processed_green_step_nongreen__stable_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.first_processed_green_wait_exact__stable_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_noncurrent_nongreen__stable_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_nongreen_outside_original__stable_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_step_current_keep__stable_transition,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.in_Znth_exists__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.waits_until_green_exists__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.waits_until_green_nonnegative__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.waits_until_green_zero_if_start_green__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.traffic_scan_exit_implies_spec__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_lib.green_current_spec_zero__final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_1_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_1_red_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_1_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_2_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_2_yellow_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_2_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_3_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_3_red_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_3_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_4_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_4_yellow_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_4_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_1_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_1_red_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_1_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_2_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_2_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_3_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_3_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_4_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_4_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_5_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_5_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_6_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_5_6_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_1_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_1_yellow_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_1_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_2_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_2_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_3_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_3_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_4_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_4_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_5_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_5_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_6_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_entail_wit_6_6_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_1_red_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_1_red,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_2_yellow_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_2_yellow,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_3_green_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P013_1744C_traffic_light_proof_manual.proof_of_solver_return_wit_3_green]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Completed traffic_light proof {decl} depends on sorryAx"
