import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_goal_check

run_cmd do
  let proved := #[``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.one_equal_pair_deletion_decompose__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.one_equal_pair_deletion_length__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_irreducible_adjacent__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_irreducible_tail__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_stack_step_irreducible__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_stack_step_involutive__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_fold_irreducible__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.one_equal_pair_deletion_fold_invariant__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_fold_irreducible_word__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_fold_irreducible_empty__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_states_invariant_nat__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_trace_invariants__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_normal_form_unique__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.one_equal_pair_deletion_compose__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.one_equal_pair_deletion_append__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.Znth_map_in_range__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_trace_append__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_trace_snoc__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.deletion_game_trace_to_pair__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.prefix_game_state_of_normal_trace__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_irreducible_prefix__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.pair_deletion_irreducible_snoc__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.list_snoc_as_sublist_last__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.prefix_game_state_push__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.prefix_game_state_pop_pair__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.sentinel_nonzero_index_bound__stack_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.terminator_zero_index_eq_length__final_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_lib.prefix_game_state_spec_parity__final_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_3_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_entail_wit_2_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_return_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_return_wit_1_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P024_1104B_game_with_string_proof_manual.proof_of_solver_return_wit_1]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "source Qed depends on sorryAx: {decl}"
  Lean.logInfo "Verified 44 source Qed declarations without sorryAx"
