import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_goal_check

run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.cake_sum_bounds_from_forall__try_initialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.sum_nonnegative_pointwise__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.sum_sublist_nonnegative__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.sum_sublist_inclusion__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.ceil_third_threshold__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.sublist_full__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.greedy_terminal_success__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.greedy_terminal_exclusion_chain__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.greedy_terminal_failure__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.greedy_terminal_try_order__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.suffix_sum_empty__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.selected_row_length__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.suffix_sum_extend__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.sum_upper_pointwise__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.suffix_sum_upper__try_terminal_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.Znth_app_left__try_output_materialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.Znth_app_last__try_output_materialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.bounded_values_sum_lower__solver_order_setup,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.order_table_decomposition__solver_order_setup,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.Forall_Znth__solver_order_iteration,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_lib.failed_six_orders_spec_none__solver_final_results,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_11_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_11_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_11,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_20_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_20_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_safety_wit_20,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3_split_goal_5,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_4_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_1_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_2_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_5_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_6_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_6_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_6,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_7_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_7_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_7_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_7,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_8,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_9_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_9,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_10_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_10_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_10_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_10,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_11_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_11_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_11_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_11,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_12_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_12,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_13_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_13,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_14,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_15,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_16_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_entail_wit_16,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_try_order_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_safety_wit_23_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_safety_wit_23_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_safety_wit_23,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_3_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_4_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_5,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_6,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_9,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_10,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_11_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_11,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_12_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_12_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_entail_wit_12,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_return_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_partial_solve_wit_2_pure_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P040_1983C_have_your_cake_and_eat_it_too_proof_manual.proof_of_solver_partial_solve_wit_2_pure
  ]
  -- C expression interpretation and aggregate type sizes are parameters of the shared memory model.
  let allowed := #[``propext, ``Classical.choice, ``Quot.sound,
    ``SimpleC.SL.CNotation.eval_addr_expr, ``SimpleC.SL.CNotation.sizeof_alias_type,
    ``SimpleC.SL.CNotation.sizeof_enum_type, ``SimpleC.SL.CNotation.sizeof_struct_type,
    ``SimpleC.SL.CNotation.sizeof_union_type]
  for decl in proved do
    for ax in (← Lean.collectAxioms decl) do
      unless allowed.contains ax do
        throwError "Source proof {decl} depends on unexpected axiom {ax}"
  Lean.logInfo "Audited 102 source Qed declarations; no sorryAx or additional mathematical axioms."
