import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib
import Lean.Util.CollectAxioms

-- All 80 source library Qed declarations, including the finite sieve count.
run_cmd do
  for decl in #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.FactorScanState2_implies_FactorScanState,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.FactorDivideState2_implies_FactorDivideState,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_index_bounds__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide_state_current_prime__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_prime_square_int64__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_aux_snoc__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_snoc__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.proper_marked_before_advance_large__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.proper_marked_before_advance_marked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_unmarked_prime__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_begin_mark__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_advance_unmarked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_advance_marked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_primes_complete__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_primes_length__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_capacity__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_mark_table2_replace_step__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_mark_table2_finish__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_complete__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_zero__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_Znth_ge_2__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_mod_zero_divides__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan_state2_initial__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan_state2_append_divisor__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide_state2_reduce__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.NoDup_firstn__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_29__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_5__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.firstn_Z_succ__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.NoDup_snoc_notin__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide2_to_scan2_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_to_scan2_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_7__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_11__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_13__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_17__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_19__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_23__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_not_divide_distinct_prime__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_rel_prime_product__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.product_distinct_primes_divides__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_nodup_prime_ten_product__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_prime_divisors_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_notin__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_cons__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_nil__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.length_as_sum_count_occ__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_filter_cons__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.transpose_filter_counts__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.zdividesb_true_iff__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.distinct_prime_divisors_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_filter_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_prime_filter_bound__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_counts_to_filters__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_length_bound__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_capacity_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.pointwise_bounds_Forall__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_divisor_exists__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_Znth_le__duplicate_loop,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.composite_small_prime_divisor__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.residual_prime_exhausted__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_before_index__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.residual_prime_square_cutoff__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.firstn_succ_Znth__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_next__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_residual_complete__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_unit_complete__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.zdividesb_true__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.two_occurrences_nat_count_occ__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.count_occ_two_occurrences_nat__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.two_occurrences_count_occ__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.Znth_map_in_range__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.filter_length_count_true__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.filter_two_indices__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_permutation__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_loop_initial__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_loop_exit__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_duplicate_spec__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_equal_step__duplicate_loop,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_unequal_step__duplicate_loop
  ] do
    for ax in ← Lean.collectAxioms decl do
      unless #[``propext, ``Classical.choice, ``Quot.sound].contains ax do
        throwError "P048 source proof {decl} depends on unexpected axiom {ax}"
