import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_goal_check
import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_library_audit

/- All 80 library and 90 manual active source Qed declarations. -/
run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.FactorScanState2_implies_FactorScanState,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.FactorDivideState2_implies_FactorDivideState,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_index_bounds__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide_state_current_prime__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_prime_square_int64__safety_prime_bounds,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_aux_snoc__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_snoc__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.proper_marked_before_advance_large__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.proper_marked_before_advance_marked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_unmarked_prime__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_begin_mark__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_advance_unmarked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_advance_marked__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_primes_complete__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.bounded_primes_length__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_capacity__sieve_construction,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_mark_table2_replace_step__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_mark_table2_finish__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_prefix_table2_complete__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_zero__sieve_marking_exits,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_Znth_ge_2__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_table_mod_zero_divides__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan_state2_initial__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan_state2_append_divisor__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide_state2_reduce__factor_scan_divide,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.NoDup_firstn__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_29__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_5__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.firstn_Z_succ__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.NoDup_snoc_notin__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_divide2_to_scan2_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_to_scan2_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_7__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_11__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_13__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_17__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_19__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_floor_23__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_not_divide_distinct_prime__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_rel_prime_product__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.product_distinct_primes_divides__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_nodup_prime_ten_product__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_prime_divisors_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_notin__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_cons__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_count_occ_nil__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.length_as_sum_count_occ__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_filter_cons__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.transpose_filter_counts__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.zdividesb_true_iff__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.distinct_prime_divisors_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_filter_length__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_prime_filter_bound__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.sum_counts_to_filters__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_length_bound__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_capacity_next__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.pointwise_bounds_Forall__factor_scan_advance,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_divisor_exists__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.increasing_Znth_le__duplicate_loop,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.composite_small_prime_divisor__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.residual_prime_exhausted__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.complete_prime_before_index__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.residual_prime_square_cutoff__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.firstn_succ_Znth__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_next__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_residual_complete__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.factor_scan2_unit_complete__factor_item_finish,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.zdividesb_true__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.two_occurrences_nat_count_occ__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.count_occ_two_occurrences_nat__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.two_occurrences_count_occ__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.Znth_map_in_range__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.filter_length_count_true__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.filter_two_indices__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_bag_prefix_permutation__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_loop_initial__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_loop_exit__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.prime_factor_duplicate_spec__duplicate_init_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_equal_step__duplicate_loop,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_lib.duplicate_scan_unequal_step__duplicate_loop,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_19_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_19_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_19,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_20_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_20_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_20,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_23_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_23_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_23,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_25_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_25_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_safety_wit_25,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_1_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_2_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_4_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_5_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_5_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_5_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_5_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_5,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_6_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_6_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_6_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_6_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_6,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7_split_goal_5,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_7,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_8_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_8_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_8_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_8_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_8,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_1_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_9_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_10_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_11_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_11_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_11,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_12_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_12_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_12,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_13_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_13_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_13_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_13_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_14_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P048_1771C_hossam_and_trainees_proof_manual.proof_of_solver_entail_wit_14
  ]
  /- The five CNotation constants are existing address/type-size interpretation parameters. -/
  let allowed := #[``propext, ``Classical.choice, ``Quot.sound,
    ``SimpleC.SL.CNotation.eval_addr_expr, ``SimpleC.SL.CNotation.sizeof_struct_type,
    ``SimpleC.SL.CNotation.sizeof_union_type, ``SimpleC.SL.CNotation.sizeof_enum_type,
    ``SimpleC.SL.CNotation.sizeof_alias_type]
  let mut allAxioms : Array Lean.Name := #[]
  for decl in proved do
    let axioms ← Lean.collectAxioms decl
    if axioms.contains ``sorryAx then
      throwError "unproved dependency in {decl}"
    for axiomName in axioms do
      unless allowed.contains axiomName do
        throwError "unexpected additional axiom {axiomName} in {decl}"
      unless allAxioms.contains axiomName do
        allAxioms := allAxioms.push axiomName
  Lean.logInfo m!"Audited {proved.size} source Qed declarations: no sorryAx. Existing axioms: {allAxioms}"
