import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_proof_auto
import SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_proof_manual

namespace SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_goal_check

open SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_proof_auto
open SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_goal.VC_Correct where
  proof_of_solver_safety_wit_1 := proof_of_solver_safety_wit_1
  proof_of_solver_safety_wit_2 := proof_of_solver_safety_wit_2
  proof_of_solver_safety_wit_3 := proof_of_solver_safety_wit_3
  proof_of_solver_safety_wit_4 := proof_of_solver_safety_wit_4
  proof_of_solver_safety_wit_5 := proof_of_solver_safety_wit_5
  proof_of_solver_safety_wit_6 := proof_of_solver_safety_wit_6
  proof_of_solver_safety_wit_7 := proof_of_solver_safety_wit_7
  proof_of_solver_safety_wit_8 := proof_of_solver_safety_wit_8
  proof_of_solver_safety_wit_9 := proof_of_solver_safety_wit_9
  proof_of_solver_safety_wit_10 := proof_of_solver_safety_wit_10
  proof_of_solver_safety_wit_11 := proof_of_solver_safety_wit_11
  proof_of_solver_safety_wit_12 := proof_of_solver_safety_wit_12
  proof_of_solver_safety_wit_15 := proof_of_solver_safety_wit_15
  proof_of_solver_safety_wit_16 := proof_of_solver_safety_wit_16
  proof_of_solver_safety_wit_17 := proof_of_solver_safety_wit_17
  proof_of_solver_safety_wit_18 := proof_of_solver_safety_wit_18
  proof_of_solver_return_wit_1 := proof_of_solver_return_wit_1
  proof_of_solver_partial_solve_wit_1_pure := proof_of_solver_partial_solve_wit_1_pure
  proof_of_solver_partial_solve_wit_1 := proof_of_solver_partial_solve_wit_1
  proof_of_solver_partial_solve_wit_2 := proof_of_solver_partial_solve_wit_2
  proof_of_solver_partial_solve_wit_3 := proof_of_solver_partial_solve_wit_3
  proof_of_solver_partial_solve_wit_4 := proof_of_solver_partial_solve_wit_4
  proof_of_solver_partial_solve_wit_5 := proof_of_solver_partial_solve_wit_5
  proof_of_solver_partial_solve_wit_6 := proof_of_solver_partial_solve_wit_6
  proof_of_solver_partial_solve_wit_7 := proof_of_solver_partial_solve_wit_7
  proof_of_solver_partial_solve_wit_8 := proof_of_solver_partial_solve_wit_8
  proof_of_solver_safety_wit_13 := proof_of_solver_safety_wit_13
  proof_of_solver_safety_wit_14 := proof_of_solver_safety_wit_14
  proof_of_solver_entail_wit_1 := proof_of_solver_entail_wit_1
  proof_of_solver_entail_wit_2 := proof_of_solver_entail_wit_2
  proof_of_solver_entail_wit_3 := proof_of_solver_entail_wit_3
  proof_of_solver_entail_wit_4_1 := proof_of_solver_entail_wit_4_1
  proof_of_solver_entail_wit_4_2 := proof_of_solver_entail_wit_4_2
  proof_of_solver_entail_wit_4_3 := proof_of_solver_entail_wit_4_3
  proof_of_solver_entail_wit_5 := proof_of_solver_entail_wit_5

end SimpleC.EE.LLM_bench.Codeforces.examples_shard00.P053_1393C_pinkie_pie_eats_patty_cakes_goal_check
