import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P020_433A_kitahara_harukis_gift_goal_check
open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P020_433A_kitahara_harukis_gift_lib
open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P020_433A_kitahara_harukis_gift_proof_manual

run_cmd do
  let proved := #[
    ``weight_values_of_explicit_require,
    ``weight_at_from_pre__prefix_scan,
    ``unit_weight_at_from_pre__prefix_scan,
    ``prefix_unit_total_step__prefix_scan,
    ``reach_table_to_inner_at_total__reach_initialization,
    ``pre_unit_weight_bounds__reach_initialization,
    ``pre_weight_classification__reach_initialization,
    ``pre_unit_sum_lower_bound__reach_initialization,
    ``combine_app_same_length__inner_dp_transitions,
    ``fold_right_Z_add_acc__inner_dp_transitions,
    ``fold_right_Z_add_singleton__inner_dp_transitions,
    ``unit_selectable_sum_app_singleton__inner_dp_transitions,
    ``unit_selectable_sum_snoc_cases__inner_dp_transitions,
    ``Forall_firstn__inner_dp_transitions,
    ``Forall_skipn__inner_dp_transitions,
    ``Forall_sublist__inner_dp_transitions,
    ``unit_selectable_sum_nonnegative__inner_dp_transitions,
    ``Zlength_replace_Znth__inner_dp_transitions,
    ``valid_Znth__inner_dp_transitions,
    ``unit_weight_quot__inner_dp_transitions,
    ``reach_inner_finish__inner_dp_transitions,
    ``reach_inner_mark_step__inner_dp_transitions,
    ``reach_inner_skip_step__inner_dp_transitions,
    ``weight_sum_unit_scale__final_result,
    ``selected_sum_unit_scale__final_result,
    ``fair_split_unit_balance__final_result,
    ``fair_split_iff_half_selectable__final_result,
    ``solver_return_bridge_of_bit__final_result,
    ``proof_of_solver_safety_wit_4_split_goal_1,
    ``proof_of_solver_safety_wit_4_split_goal_2,
    ``proof_of_solver_safety_wit_4,
    ``proof_of_solver_entail_wit_1_split_goal_1,
    ``proof_of_solver_entail_wit_1_split_goal_2,
    ``proof_of_solver_entail_wit_1,
    ``proof_of_solver_entail_wit_2_split_goal_1,
    ``proof_of_solver_entail_wit_2_split_goal_2,
    ``proof_of_solver_entail_wit_2_split_goal_3,
    ``proof_of_solver_entail_wit_2,
    ``proof_of_solver_entail_wit_3_split_goal_1,
    ``proof_of_solver_entail_wit_3_split_goal_2,
    ``proof_of_solver_entail_wit_3_split_goal_3,
    ``proof_of_solver_entail_wit_3_split_goal_4,
    ``proof_of_solver_entail_wit_3,
    ``proof_of_solver_entail_wit_4_split_goal_1,
    ``proof_of_solver_entail_wit_4_split_goal_2,
    ``proof_of_solver_entail_wit_4_split_goal_spatial,
    ``proof_of_solver_entail_wit_4,
    ``proof_of_solver_entail_wit_5_split_goal_1,
    ``proof_of_solver_entail_wit_5_split_goal_spatial,
    ``proof_of_solver_entail_wit_5,
    ``proof_of_solver_entail_wit_6_split_goal_1,
    ``proof_of_solver_entail_wit_6_split_goal_2,
    ``proof_of_solver_entail_wit_6,
    ``proof_of_solver_entail_wit_7_split_goal_1,
    ``proof_of_solver_entail_wit_7,
    ``proof_of_solver_entail_wit_8_split_goal_1,
    ``proof_of_solver_entail_wit_8_split_goal_2,
    ``proof_of_solver_entail_wit_8_split_goal_3,
    ``proof_of_solver_entail_wit_8_split_goal_4,
    ``proof_of_solver_entail_wit_8_split_goal_5,
    ``proof_of_solver_entail_wit_8,
    ``proof_of_solver_entail_wit_9_split_goal_1,
    ``proof_of_solver_entail_wit_9_split_goal_2,
    ``proof_of_solver_entail_wit_9,
    ``proof_of_solver_entail_wit_10_1_split_goal_1,
    ``proof_of_solver_entail_wit_10_1,
    ``proof_of_solver_entail_wit_10_2_split_goal_1,
    ``proof_of_solver_entail_wit_10_2,
    ``proof_of_solver_entail_wit_11_split_goal_1,
    ``proof_of_solver_entail_wit_11,
    ``proof_of_solver_entail_wit_12_split_goal_1,
    ``proof_of_solver_entail_wit_12_split_goal_2,
    ``proof_of_solver_entail_wit_12_split_goal_3,
    ``proof_of_solver_entail_wit_12_split_goal_4,
    ``proof_of_solver_entail_wit_12_split_goal_5,
    ``proof_of_solver_entail_wit_12_split_goal_6,
    ``proof_of_solver_entail_wit_12,
    ``proof_of_solver_return_wit_1,
    ``proof_of_solver_return_wit_2
  ]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Source Qed {decl} depends on sorryAx"
  Lean.logInfo "P020 gift: all 79 source Qed recursively audited without sorryAx"
