import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_proof_auto
import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_proof_manual

namespace SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_goal_check

open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_proof_auto
open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_goal.VC_Correct where
  proof_of_next_parity_safety_wit_1 := proof_of_next_parity_safety_wit_1
  proof_of_next_parity_safety_wit_2 := proof_of_next_parity_safety_wit_2
  proof_of_next_parity_safety_wit_3 := proof_of_next_parity_safety_wit_3
  proof_of_next_parity_safety_wit_4 := proof_of_next_parity_safety_wit_4
  proof_of_solver_safety_wit_1 := proof_of_solver_safety_wit_1
  proof_of_solver_safety_wit_2 := proof_of_solver_safety_wit_2
  proof_of_solver_safety_wit_3 := proof_of_solver_safety_wit_3
  proof_of_solver_safety_wit_4 := proof_of_solver_safety_wit_4
  proof_of_solver_safety_wit_5 := proof_of_solver_safety_wit_5
  proof_of_solver_safety_wit_6 := proof_of_solver_safety_wit_6
  proof_of_solver_partial_solve_wit_1 := proof_of_solver_partial_solve_wit_1
  proof_of_solver_partial_solve_wit_2 := proof_of_solver_partial_solve_wit_2
  proof_of_solver_partial_solve_wit_3 := proof_of_solver_partial_solve_wit_3
  proof_of_solver_partial_solve_wit_4 := proof_of_solver_partial_solve_wit_4
  proof_of_next_parity_return_wit_1 := proof_of_next_parity_return_wit_1
  proof_of_solver_entail_wit_1 := proof_of_solver_entail_wit_1
  proof_of_solver_entail_wit_2_1 := proof_of_solver_entail_wit_2_1
  proof_of_solver_entail_wit_2_2 := proof_of_solver_entail_wit_2_2
  proof_of_solver_return_wit_1 := proof_of_solver_return_wit_1
  proof_of_solver_partial_solve_wit_2_pure := proof_of_solver_partial_solve_wit_2_pure

end SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P022_705B_spider_man_goal_check
