import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_auto
import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual

namespace SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_goal_check

open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_auto
open SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_goal.VC_Correct where
  proof_of_llabs_safety_wit_1 := proof_of_llabs_safety_wit_1
  proof_of_llabs_safety_wit_2 := proof_of_llabs_safety_wit_2
  proof_of_gcdll_safety_wit_1 := proof_of_gcdll_safety_wit_1
  proof_of_gcdll_safety_wit_2 := proof_of_gcdll_safety_wit_2
  proof_of_gcdll_safety_wit_3 := proof_of_gcdll_safety_wit_3
  proof_of_gcdll_entail_wit_1 := proof_of_gcdll_entail_wit_1
  proof_of_pair_fill_safety_wit_1 := proof_of_pair_fill_safety_wit_1
  proof_of_pair_fill_safety_wit_3 := proof_of_pair_fill_safety_wit_3
  proof_of_pair_fill_safety_wit_5 := proof_of_pair_fill_safety_wit_5
  proof_of_pair_fill_partial_solve_wit_1_pure := proof_of_pair_fill_partial_solve_wit_1_pure
  proof_of_pair_fill_partial_solve_wit_1 := proof_of_pair_fill_partial_solve_wit_1
  proof_of_pair_fill_partial_solve_wit_2_pure := proof_of_pair_fill_partial_solve_wit_2_pure
  proof_of_pair_fill_partial_solve_wit_2 := proof_of_pair_fill_partial_solve_wit_2
  proof_of_pair_fill_partial_solve_wit_3 := proof_of_pair_fill_partial_solve_wit_3
  proof_of_pair_fill_partial_solve_wit_4 := proof_of_pair_fill_partial_solve_wit_4
  proof_of_pair_fill_partial_solve_wit_5 := proof_of_pair_fill_partial_solve_wit_5
  proof_of_solver_safety_wit_1 := proof_of_solver_safety_wit_1
  proof_of_solver_safety_wit_2 := proof_of_solver_safety_wit_2
  proof_of_solver_safety_wit_3 := proof_of_solver_safety_wit_3
  proof_of_solver_safety_wit_4 := proof_of_solver_safety_wit_4
  proof_of_solver_safety_wit_5 := proof_of_solver_safety_wit_5
  proof_of_solver_safety_wit_6 := proof_of_solver_safety_wit_6
  proof_of_solver_safety_wit_7 := proof_of_solver_safety_wit_7
  proof_of_solver_safety_wit_8 := proof_of_solver_safety_wit_8
  proof_of_solver_safety_wit_9 := proof_of_solver_safety_wit_9
  proof_of_solver_safety_wit_10 := proof_of_solver_safety_wit_10
  proof_of_solver_safety_wit_11 := proof_of_solver_safety_wit_11
  proof_of_solver_safety_wit_12 := proof_of_solver_safety_wit_12
  proof_of_solver_safety_wit_13 := proof_of_solver_safety_wit_13
  proof_of_solver_safety_wit_14 := proof_of_solver_safety_wit_14
  proof_of_solver_safety_wit_15 := proof_of_solver_safety_wit_15
  proof_of_solver_safety_wit_16 := proof_of_solver_safety_wit_16
  proof_of_solver_safety_wit_17 := proof_of_solver_safety_wit_17
  proof_of_solver_safety_wit_18 := proof_of_solver_safety_wit_18
  proof_of_solver_safety_wit_21 := proof_of_solver_safety_wit_21
  proof_of_solver_safety_wit_22 := proof_of_solver_safety_wit_22
  proof_of_solver_safety_wit_23 := proof_of_solver_safety_wit_23
  proof_of_solver_safety_wit_24 := proof_of_solver_safety_wit_24
  proof_of_solver_safety_wit_25 := proof_of_solver_safety_wit_25
  proof_of_solver_safety_wit_26 := proof_of_solver_safety_wit_26
  proof_of_solver_safety_wit_27 := proof_of_solver_safety_wit_27
  proof_of_solver_safety_wit_28 := proof_of_solver_safety_wit_28
  proof_of_solver_safety_wit_29 := proof_of_solver_safety_wit_29
  proof_of_solver_safety_wit_30 := proof_of_solver_safety_wit_30
  proof_of_solver_safety_wit_31 := proof_of_solver_safety_wit_31
  proof_of_solver_safety_wit_32 := proof_of_solver_safety_wit_32
  proof_of_solver_safety_wit_33 := proof_of_solver_safety_wit_33
  proof_of_solver_safety_wit_34 := proof_of_solver_safety_wit_34
  proof_of_solver_safety_wit_35 := proof_of_solver_safety_wit_35
  proof_of_solver_safety_wit_36 := proof_of_solver_safety_wit_36
  proof_of_solver_safety_wit_37 := proof_of_solver_safety_wit_37
  proof_of_solver_safety_wit_38 := proof_of_solver_safety_wit_38
  proof_of_solver_safety_wit_39 := proof_of_solver_safety_wit_39
  proof_of_solver_safety_wit_40 := proof_of_solver_safety_wit_40
  proof_of_solver_partial_solve_wit_1 := proof_of_solver_partial_solve_wit_1
  proof_of_solver_partial_solve_wit_2 := proof_of_solver_partial_solve_wit_2
  proof_of_solver_partial_solve_wit_3 := proof_of_solver_partial_solve_wit_3
  proof_of_solver_partial_solve_wit_4 := proof_of_solver_partial_solve_wit_4
  proof_of_solver_partial_solve_wit_5 := proof_of_solver_partial_solve_wit_5
  proof_of_solver_partial_solve_wit_6 := proof_of_solver_partial_solve_wit_6
  proof_of_solver_partial_solve_wit_7 := proof_of_solver_partial_solve_wit_7
  proof_of_solver_partial_solve_wit_8 := proof_of_solver_partial_solve_wit_8
  proof_of_solver_partial_solve_wit_9 := proof_of_solver_partial_solve_wit_9
  proof_of_solver_partial_solve_wit_10 := proof_of_solver_partial_solve_wit_10
  proof_of_solver_partial_solve_wit_11 := proof_of_solver_partial_solve_wit_11
  proof_of_solver_partial_solve_wit_12 := proof_of_solver_partial_solve_wit_12
  proof_of_solver_partial_solve_wit_13 := proof_of_solver_partial_solve_wit_13
  proof_of_solver_partial_solve_wit_14 := proof_of_solver_partial_solve_wit_14
  proof_of_solver_partial_solve_wit_15 := proof_of_solver_partial_solve_wit_15
  proof_of_solver_partial_solve_wit_16 := proof_of_solver_partial_solve_wit_16
  proof_of_solver_partial_solve_wit_17_pure := proof_of_solver_partial_solve_wit_17_pure
  proof_of_solver_partial_solve_wit_17 := proof_of_solver_partial_solve_wit_17
  proof_of_solver_partial_solve_wit_18_pure := proof_of_solver_partial_solve_wit_18_pure
  proof_of_solver_partial_solve_wit_18 := proof_of_solver_partial_solve_wit_18
  proof_of_llabs_return_wit_1 := proof_of_llabs_return_wit_1
  proof_of_llabs_return_wit_2 := proof_of_llabs_return_wit_2
  proof_of_gcdll_entail_wit_2 := proof_of_gcdll_entail_wit_2
  proof_of_gcdll_return_wit_1 := proof_of_gcdll_return_wit_1
  proof_of_pair_fill_safety_wit_2 := proof_of_pair_fill_safety_wit_2
  proof_of_pair_fill_safety_wit_4 := proof_of_pair_fill_safety_wit_4
  proof_of_pair_fill_return_wit_1 := proof_of_pair_fill_return_wit_1
  proof_of_pair_fill_partial_solve_wit_3_pure := proof_of_pair_fill_partial_solve_wit_3_pure
  proof_of_solver_safety_wit_19 := proof_of_solver_safety_wit_19
  proof_of_solver_safety_wit_20 := proof_of_solver_safety_wit_20
  proof_of_solver_entail_wit_1 := proof_of_solver_entail_wit_1
  proof_of_solver_entail_wit_2 := proof_of_solver_entail_wit_2
  proof_of_solver_entail_wit_3_1 := proof_of_solver_entail_wit_3_1
  proof_of_solver_entail_wit_3_2 := proof_of_solver_entail_wit_3_2
  proof_of_solver_entail_wit_3_3 := proof_of_solver_entail_wit_3_3
  proof_of_solver_entail_wit_3_4 := proof_of_solver_entail_wit_3_4
  proof_of_solver_entail_wit_4_1 := proof_of_solver_entail_wit_4_1
  proof_of_solver_entail_wit_4_2 := proof_of_solver_entail_wit_4_2
  proof_of_solver_entail_wit_5_1 := proof_of_solver_entail_wit_5_1
  proof_of_solver_entail_wit_5_2 := proof_of_solver_entail_wit_5_2
  proof_of_solver_entail_wit_6_1 := proof_of_solver_entail_wit_6_1
  proof_of_solver_entail_wit_6_2 := proof_of_solver_entail_wit_6_2
  proof_of_solver_return_wit_1 := proof_of_solver_return_wit_1
  proof_of_solver_return_wit_2 := proof_of_solver_return_wit_2

end SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_goal_check
