import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_goal_check

run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.gcd_abs_positive__pair_fill,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.pair_output_prefix__pair_fill,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.output_prefix_three_case1__solver_initialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.output_prefix_three_case2__solver_initialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.output_prefix_three_case3__solver_initialization,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.combine_app__loop_extension,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.output_prefix_append_pair__loop_extension,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_lib.output_prefix_to_spec_by_parity__final_result,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_llabs_return_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_llabs_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_llabs_return_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_llabs_return_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_entail_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_entail_wit_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_entail_wit_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_return_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_gcdll_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_safety_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_partial_solve_wit_3_pure_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_partial_solve_wit_3_pure_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_partial_solve_wit_3_pure_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_partial_solve_wit_3_pure_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_pair_fill_partial_solve_wit_3_pure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_safety_wit_19_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_safety_wit_19,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_safety_wit_20_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_safety_wit_20_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_safety_wit_20,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_2_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_3_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_4_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_4_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_4_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_4_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_1_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_2_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_5_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_6_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_entail_wit_6_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P047_1582D_vupsen_pupsen_and_0_proof_manual.proof_of_solver_return_wit_2
  ]
  for decl in proved do
    if (← Lean.collectAxioms decl).contains ``sorryAx then
      throwError "Source Qed {decl} depends on sorryAx"
  Lean.logInfo "P047: all 60 source Qed recursively audited without sorryAx"
