import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib

/- Every active source library Qed is checked recursively. -/
run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.OnSet_fold_upper_bound__outer_loop_component_commit,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.MaxImpostersOn_upper_bound__outer_loop_component_commit,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.Zlength_replace_Znth__forward_star_build_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.AdjChain_ext__forward_star_build_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.triple_src__forward_star_build_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.triple_dst__forward_star_build_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.triple_wt__forward_star_build_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_right_add_zero_of_Znth_zero__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.Zlength_zeros__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.Znth_zeros__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_right_add_zeros__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.max_imposters_on_empty__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.singleton_component_frontier_strong__outer_loop_entry,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.sublist_pop_permutation__frontier_pop_to_scan,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.nodup_app_keep_head__frontier_pop_to_scan,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.nodup_bounded_Zlength__frontier_pop_to_scan,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.colour_counts_cover__frontier_pop_to_scan,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_frontier_pop_to_scan__frontier_pop_to_scan,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.Znth_In__scan_conflict,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.scan_conflict_spec__scan_conflict,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.In_Zseq_iff__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.sublist_replace_append__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.nodup_vertex_range_Zlength__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_scan_pending_top_lt__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_scan_advance_existing__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.colour_values_replace__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fully_scanned_replace_fresh__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.colour_count_replace_fresh__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.scan_at_owned_advance_new__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.Znth_In_bounds__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.xor_relation_sym__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.xor_extend_flip__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.contract_disj_xor__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.roles_consistent_edge__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.roles_consistent_local_edge__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_two_choices_extend__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_two_choices_local_extend__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.new_colour_set_extend__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_scan_advance_new__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_scan_advance_new_stack__scan_edge_transitions,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_scan_done__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.new_component_edge_closed__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.lxor_bit__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.lxor_shuffle__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.edge_forward__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.edge_reverse__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.comment_bounds_from_forward_star__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.frontier_respected_closed__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.znth_replace_same__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.znth_replace_diff__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.sum_replace__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_replace_length__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_replace_member__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_replace_outside__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_replace_sum__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.binary_sum_count__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_bit_sum__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.extend_consistent__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.fold_replace_sum_general__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.restrict_consistent__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.consistent_on_vertices__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_roles_sum__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.sum_map_zero__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_max_lift__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.component_frontier_complete__scan_and_component_closure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.xor_roles_equiv__final_specification,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.roles_consistent_iff_consistent_on_total__final_specification,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P053_1594D_the_number_of_imposters_lib.max_imposters_on_total_implies_spec__final_specification
  ]
  for decl in proved do
    let axioms ← Lean.collectAxioms decl
    for ax in axioms do
      unless #[``propext,``Quot.sound,``Classical.choice].contains ax do
        throwError "Unexpected axiom {ax} in {decl}"
  Lean.logInfo m!"Audited all {proved.size} source library Qed declarations: standard logical axioms only; no sorryAx."
