import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_goal_check

run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_mask_set_next__row_mask_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_mask_clear_next__row_mask_step,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_mask_complete_unique__representative_update,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.representative_insert__representative_update,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.representative_skip__representative_update,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.no_cover_outer_missing__cover_search,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.no_cover_inner_missing__cover_search,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.no_cover_inner_noncover__cover_search,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_mask_prefix_exists__feasible_outcomes,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_masks_lor_full__feasible_outcomes,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.row_masks_cover_pair__feasible_outcomes,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.completed_no_cover_excludes_feasible__feasible_outcomes,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.quot_nonnegative__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.half_positive__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.half_less_than_input__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.Znth_concat_uniform__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.matrix_entries_bounded_from_flat__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.matrix_entry_bounds__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.combined_entry_bounds__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.pair_score_bounds__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.pair_at_least_score_lower_bound__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.pair_score_implies_pair_at_least__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.pair_at_least_zero__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.optimal_pair_score_exists__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.optimal_pair_score_bounds__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.feasible_threshold_optimal_bound__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_lib.optimal_pair_to_spec__solver_semantics,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_2_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_2_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_14_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_14_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_14_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_14_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_safety_wit_14,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_3_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_3_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_4_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_2_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_5_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_1_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_2_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_6_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_7_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_7_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_7_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_7,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_8_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_8,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_9_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_9_1_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_9_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_9_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_9_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_10_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_10_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_10_2_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_entail_wit_10_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_return_wit_1_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_return_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_feasible_which_implies_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_4_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_4_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_12_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_12_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_safety_wit_12,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_entail_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_entail_wit_4_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_entail_wit_4_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_return_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_return_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_return_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_3_pure_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_3_pure_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_3_pure_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_3_pure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_4_pure_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_4_pure_split_goal_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_4_pure_split_goal_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_4_pure_split_goal_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_4_pure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_7_pure_split_goal_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_partial_solve_wit_7_pure,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_1,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_2,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_3_split_goal_spatial,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_3,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_4,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P066_1288D_minimax_problem_proof_manual.proof_of_solver_which_implies_wit_5
  ]
  -- Shared C memory-model parameters appear in the types of spatial verification conditions.
  let allowed := #[``propext, ``Classical.choice, ``Quot.sound,
    ``SimpleC.SL.CNotation.eval_addr_expr, ``SimpleC.SL.CNotation.sizeof_alias_type,
    ``SimpleC.SL.CNotation.sizeof_enum_type, ``SimpleC.SL.CNotation.sizeof_struct_type,
    ``SimpleC.SL.CNotation.sizeof_union_type]
  for decl in proved do
    for ax in (← Lean.collectAxioms decl) do
      unless allowed.contains ax do
        throwError "Source proof {decl} depends on unexpected axiom {ax}"
  Lean.logInfo "Audited 115 source Qed/Defined declarations; no sorryAx or additional mathematical axioms."
