import SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib

/- All active source library Qed declarations, excluding nested Coq comments. -/
run_cmd do
  let proved := #[
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.neighbor_conflict_five_colour_choice__colour_selection,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.can_place_one_iff_legal_color__solver_colour_search,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.five_colour_neighbour_available__solver_colour_search,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_side_extend__solver_greedy_side,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.replace_nth_length__solver_paint,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.zlength_replace_Znth__solver_paint,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_rectangle_prefix_replace_step__solver_paint,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.canonical_grid_replace__solver_paint,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_prefix_replace__solver_paint,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.Znth_In_range__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.rows_of_flat_nat__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.rows_of_flat_from_length__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_rectangle_index_ge_anchor__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_rectangle_membership__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.trace_bounds_and_canonical__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.Znth_concat_rect__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.rows_of_flat_Znth__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.rows_of_flat_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_rectangle_coordinate__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.lex_first_difference__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.adjcell_cases__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_step__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_refl__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_prepend__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.manhattan_row_up__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.manhattan_row_down__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.manhattan_col_up__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.manhattan_col_down__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.rectangle_connected__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.path_region_induction__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_closed__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.sealed_component_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_append__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_endpoint_color__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.old_component_preserved__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.partial_components_place__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_components__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.Forall_from_Znth__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.Zlength_concat_rect__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.complete_partial_tiling_implies_spec__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.square_tiling_rows__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.square_tiling_flat_color__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_preserves_nonzero__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.trace_colored_origin__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.trace_colored_component_origin__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_frontier_conflict_equiv__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.least_legal_color_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.settled_side_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.paint_rectangle_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_side_length_exchange__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.lex_prefix_skip__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.lex_prefix_place__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_structural_state__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_partial_from_lex__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.smaller_conflict_has_painted_neighbour__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.smaller_conflict_has_earlier_component__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.nonnegative_anchor_strong_induction__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.local_first_difference_implies_lex__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.square_tiling_component__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.exact_component_boundary_color__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.square_anchor_le_member__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_component_not_short_before__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.component_top_left_prefix__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.component_prefix_cut__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_component_at_output_anchor__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_component_covers_output_prefix__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.first_cell_component_dichotomy__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.exact_component_reanchor__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_component_at_output_member__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_component_not_short_before_member__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.conflict_zero_has_earlier_component__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_state_unique__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_prefix_persistence__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.earlier_rectangle_crossing_geometry__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.conflict_component_crosses_candidate__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.trace_existing_component_origin_before__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.conflict_zero_has_painted_neighbour__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.lower_conflict_has_crossing_component__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.base_exchange_from_extend_ih__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.shrink_exchange_from_extend_ih__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extend_first_is_frontier__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.trace_skip_interval__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.placed_trace_at_frontier__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.least_legal_frontier_equiv__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.frontier_zero_is_new_origin__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.frontier_zero_fallback_bound__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.existing_frontier_exchange_from_extend_ih__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extend_fallback_from_ih__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.Znth_rev_inrange__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.adjcell_sym__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_sym__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.same_color_path_trans__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.exact_components_rectangles_disjoint__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.disjoint_rectangles_separate__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.earlier_component_excluded_from_candidate_square__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extension_candidate_square_empty__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.earlier_candidate_component_not_short__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.candidate_boundary_cell_cannot_match__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extension_candidate_can_place__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extend_exchange_from_ih__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.extend_exchange__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.first_difference_bound__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_lex__solver_final,
    ``SimpleC.EE.LLM_bench.Codeforces.examples_shard09.P081_432E_square_tiling_lib.greedy_trace_implies_partial_tiling__solver_final
  ]
  for decl in proved do
    let axioms ← Lean.collectAxioms decl
    for ax in axioms do
      unless #[``propext,``Quot.sound,``Classical.choice].contains ax do
        throwError "Unexpected axiom {ax} in {decl}"
  Lean.logInfo m!"Audited all {proved.size} library source Qed declarations: standard logical axioms only; no sorryAx."
