import SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_goal_check

open SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_goal.VC_Correct where
  proof_of_majorityElement_safety_wit_1 := proof_of_majorityElement_safety_wit_1
  proof_of_majorityElement_safety_wit_2 := proof_of_majorityElement_safety_wit_2
  proof_of_majorityElement_safety_wit_3 := proof_of_majorityElement_safety_wit_3
  proof_of_majorityElement_safety_wit_4 := proof_of_majorityElement_safety_wit_4
  proof_of_majorityElement_safety_wit_5 := proof_of_majorityElement_safety_wit_5
  proof_of_majorityElement_safety_wit_6 := proof_of_majorityElement_safety_wit_6
  proof_of_majorityElement_safety_wit_7 := proof_of_majorityElement_safety_wit_7
  proof_of_majorityElement_safety_wit_8 := proof_of_majorityElement_safety_wit_8
  proof_of_majorityElement_safety_wit_9 := proof_of_majorityElement_safety_wit_9
  proof_of_majorityElement_safety_wit_10 := proof_of_majorityElement_safety_wit_10
  proof_of_majorityElement_safety_wit_11 := proof_of_majorityElement_safety_wit_11
  proof_of_majorityElement_safety_wit_12 := proof_of_majorityElement_safety_wit_12
  proof_of_majorityElement_safety_wit_13 := proof_of_majorityElement_safety_wit_13
  proof_of_majorityElement_safety_wit_14 := proof_of_majorityElement_safety_wit_14
  proof_of_majorityElement_partial_solve_wit_1 := proof_of_majorityElement_partial_solve_wit_1
  proof_of_majorityElement_partial_solve_wit_2 := proof_of_majorityElement_partial_solve_wit_2
  proof_of_majorityElement_partial_solve_wit_3 := proof_of_majorityElement_partial_solve_wit_3
  proof_of_majorityElement_entail_wit_1 := proof_of_majorityElement_entail_wit_1
  proof_of_majorityElement_entail_wit_2_1 := proof_of_majorityElement_entail_wit_2_1
  proof_of_majorityElement_entail_wit_2_2 := proof_of_majorityElement_entail_wit_2_2
  proof_of_majorityElement_entail_wit_2_3 := proof_of_majorityElement_entail_wit_2_3
  proof_of_majorityElement_return_wit_1 := proof_of_majorityElement_return_wit_1

end SimpleC.EE.LLM_bench.Algorithms.majority_element.majority_element_goal_check
