import SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_proof_auto
import SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_proof_manual

namespace SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_goal_check

open SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_proof_auto
open SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_proof_manual

def VC_Correctness : SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_goal.VC_Correct where
  proof_of_chinese_remainder_theorem_safety_wit_1 := proof_of_chinese_remainder_theorem_safety_wit_1
  proof_of_chinese_remainder_theorem_safety_wit_2 := proof_of_chinese_remainder_theorem_safety_wit_2
  proof_of_chinese_remainder_theorem_safety_wit_4 := proof_of_chinese_remainder_theorem_safety_wit_4
  proof_of_chinese_remainder_theorem_safety_wit_5 := proof_of_chinese_remainder_theorem_safety_wit_5
  proof_of_chinese_remainder_theorem_safety_wit_6 := proof_of_chinese_remainder_theorem_safety_wit_6
  proof_of_chinese_remainder_theorem_safety_wit_8 := proof_of_chinese_remainder_theorem_safety_wit_8
  proof_of_chinese_remainder_theorem_safety_wit_10 := proof_of_chinese_remainder_theorem_safety_wit_10
  proof_of_chinese_remainder_theorem_safety_wit_12 := proof_of_chinese_remainder_theorem_safety_wit_12
  proof_of_chinese_remainder_theorem_safety_wit_13 := proof_of_chinese_remainder_theorem_safety_wit_13
  proof_of_chinese_remainder_theorem_safety_wit_14 := proof_of_chinese_remainder_theorem_safety_wit_14
  proof_of_chinese_remainder_theorem_safety_wit_15 := proof_of_chinese_remainder_theorem_safety_wit_15
  proof_of_chinese_remainder_theorem_safety_wit_16 := proof_of_chinese_remainder_theorem_safety_wit_16
  proof_of_chinese_remainder_theorem_safety_wit_18 := proof_of_chinese_remainder_theorem_safety_wit_18
  proof_of_chinese_remainder_theorem_safety_wit_19 := proof_of_chinese_remainder_theorem_safety_wit_19
  proof_of_chinese_remainder_theorem_partial_solve_wit_1 := proof_of_chinese_remainder_theorem_partial_solve_wit_1
  proof_of_chinese_remainder_theorem_partial_solve_wit_2 := proof_of_chinese_remainder_theorem_partial_solve_wit_2
  proof_of_chinese_remainder_theorem_partial_solve_wit_3 := proof_of_chinese_remainder_theorem_partial_solve_wit_3
  proof_of_chinese_remainder_theorem_partial_solve_wit_4 := proof_of_chinese_remainder_theorem_partial_solve_wit_4
  proof_of_chinese_remainder_theorem_partial_solve_wit_5 := proof_of_chinese_remainder_theorem_partial_solve_wit_5
  proof_of_chinese_remainder_theorem_safety_wit_3 := proof_of_chinese_remainder_theorem_safety_wit_3
  proof_of_chinese_remainder_theorem_safety_wit_7 := proof_of_chinese_remainder_theorem_safety_wit_7
  proof_of_chinese_remainder_theorem_safety_wit_9 := proof_of_chinese_remainder_theorem_safety_wit_9
  proof_of_chinese_remainder_theorem_safety_wit_11 := proof_of_chinese_remainder_theorem_safety_wit_11
  proof_of_chinese_remainder_theorem_safety_wit_17 := proof_of_chinese_remainder_theorem_safety_wit_17
  proof_of_chinese_remainder_theorem_entail_wit_1 := proof_of_chinese_remainder_theorem_entail_wit_1
  proof_of_chinese_remainder_theorem_entail_wit_2 := proof_of_chinese_remainder_theorem_entail_wit_2
  proof_of_chinese_remainder_theorem_entail_wit_3 := proof_of_chinese_remainder_theorem_entail_wit_3
  proof_of_chinese_remainder_theorem_entail_wit_4_1 := proof_of_chinese_remainder_theorem_entail_wit_4_1
  proof_of_chinese_remainder_theorem_entail_wit_4_2 := proof_of_chinese_remainder_theorem_entail_wit_4_2
  proof_of_chinese_remainder_theorem_return_wit_1 := proof_of_chinese_remainder_theorem_return_wit_1
  proof_of_chinese_remainder_theorem_partial_solve_wit_4_pure := proof_of_chinese_remainder_theorem_partial_solve_wit_4_pure

end SimpleC.EE.LLM_bench.Algorithms.chinese_remainder_theorem.chinese_remainder_theorem_goal_check
